import test from 'node:test';
import assert from 'node:assert/strict';
import evaluate from '../api/evaluate.mjs';
import checkout from '../api/checkout.mjs';
const res=()=>({code:0,setHeader(){},status(c){this.code=c;return this;},json(b){this.body=b;return this;},end(){return this;}});
const settings={PAID_AI_ENABLED:'true',PAYPAL_MODE:'live',PAYPAL_CLIENT_ID:'fixture',PAYPAL_CLIENT_SECRET:'fixture',PAYPAL_PRO_PLAN_ID:'P-FIXTURE',PAYPAL_WEBHOOK_ID:'WH-FIXTURE',OPENAI_API_KEY:'fixture',SUPABASE_URL:'https://fixture.test',SUPABASE_PUBLISHABLE_KEY:'fixture',SUPABASE_SERVICE_ROLE_KEY:'fixture'};
const body={category:'hr',language:'english',responses:Array.from({length:15},(_,i)=>({questionId:String(i),question:'Explain an example',answer:'I provided an example.'}))};
test('missing settings fail closed before provider calls',async()=>{delete process.env.PAID_AI_ENABLED;const r=res();await evaluate({method:'POST',headers:{},body},r);assert.equal(r.code,503);});
test('invalid CV and voice never reach account or AI provider',async()=>{Object.assign(process.env,settings);const original=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw Error('Unexpected call');};try{for(const input of [{...body,cvText:'private',cvConsent:true},{...body,voice:{question:'Introduce yourself',format:'webm',audioBase64:'invalid'}}]){const r=res();await evaluate({method:'POST',headers:{},body:input},r);assert.equal(r.code,400);}assert.equal(calls,0);}finally{global.fetch=original;}});
test('billing remains closed without activation flag after authentication',async()=>{delete process.env.BILLING_ENABLED;const original=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({id:'12345678-1234-1234-1234-123456789012'})});try{const r=res();await checkout({method:'POST',headers:{authorization:'Bearer fixture'},body:{plan:'pro'}},r);assert.equal(r.code,503);}finally{global.fetch=original;}});
