import {languages,preferredLanguage,rememberLanguage,translate} from './locales.mjs';
import {adminCopy} from './admin-copy.mjs';
import {coachingCopy} from './coaching-copy.mjs';
import {syncLanguageLinks} from './language-navigation.mjs';
const $=id=>document.getElementById(id),node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=String(text);if(cls)n.className=cls;return n;};
let language=preferredLanguage(),data=null,paymentData=null,noticeKey='',reviewFocused=false;
const t=k=>adminCopy[k]?.[Object.keys(languages).indexOf(language)]||coachingCopy[k]?.[Object.keys(languages).indexOf(language)]||k;
const statusLabel=k=>k==='active'?t('activeStatus'):coachingCopy[k]?.[Object.keys(languages).indexOf(language)]||t(k);
const date=x=>x&&Number.isFinite(Date.parse(x))?new Date(x).toLocaleString(languages[language].code,{dateStyle:'medium',timeStyle:'short'}):'—';
const money=(c,currency='USD')=>{try{return Number.isFinite(Number(c))?new Intl.NumberFormat(languages[language].code,{style:'currency',currency}).format(c/100):'—';}catch{return '—';}};
const value=x=>x===null||x===undefined?t('unavailable'):String(x);
const session=()=>{try{const s=JSON.parse(sessionStorage.getItem('mostaed_account')||'null');return s?.expires_at*1000>Date.now()?s:null;}catch{return null;}};
async function request(path,body){const s=session();if(!s){const e=Error();e.status=401;throw e;}const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+s.access_token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(55000)});const d=await r.json();if(!r.ok){const e=Error();e.status=r.status;throw e;}return d;}
const message=k=>{noticeKey=k;$('adminNotice').textContent=k?t(k):'';};
const environment=x=>$('mode').value==='all'||x.test_mode===($('mode').value==='sandbox');
const matches=x=>{const q=$('search').value.trim().toLowerCase();return !q||Object.values(x).some(v=>typeof v==='string'&&v.toLowerCase().includes(q));};
function table(root,headers,rows){root.replaceChildren();if(!rows.length){root.append(node('p',t('empty'),'admin-empty'));return;}const wrap=node('div',null,'admin-table-wrap'),tab=node('table',null,'admin-table'),head=node('thead'),tr=node('tr');for(const h of headers){const th=node('th',t(h));th.scope='col';tr.append(th);}head.append(tr);tab.append(head);const body=node('tbody');for(const cells of rows){const r=node('tr');for(const item of cells){const td=node('td');td.append(item instanceof Node?item:document.createTextNode(String(item??'—')));r.append(td);}body.append(r);}tab.append(body);wrap.append(tab);root.append(wrap);}
function unavailable(root){root.replaceChildren(node('p',t('error'),'admin-warning'));}
function person(x){const el=node('div',x.account_name||x.name||x.email||x.user_id||x.id);if(x.email)el.append(node('small',x.email));if(x.user_id)el.append(node('small',x.user_id));return el;}
function ref(x,extra){const el=node('div',x||'—');if(extra)el.append(node('small',extra));return el;}
function button(label,fn){const b=node('button',t(label),'btn secondary');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){message(e.status===403?'denied':'error');}finally{b.disabled=false;}};return b;}
function render(){
 if(!data)return;
 $('adminContent').hidden=false;
 const mode=$('mode').value,summary=data.summary;
 const count=summary.sessions?mode==='all'?summary.sessions.live+summary.sessions.sandbox:summary.sessions[mode]:null;
 $('metrics').replaceChildren(...[['registered',summary.accounts],['freeAccounts',summary.freeAccounts],['pendingCoaches',summary.coaches?.pending],['sessions',count]].map(([k,v])=>{const c=node('article',null,'admin-metric');c.append(node('span',t(k)),node('strong',value(v)));return c;}));
 const modeList=mode==='all'?['live','sandbox']:[mode],planRows=[];
 for(const m of modeList)for(const p of ['starter','pro']){if($('planFilter').value!=='all'&&$('planFilter').value!==p)continue;const s=summary.plans[m][p];planRows.push([p==='pro'?'AI Pro':'AI Starter',t(m),value(s.submitted),value(s.active),value(s.records)]);}
 table($('planCounts'),['plan','mode','submitted','active','records'],planRows);
 if(data.subscriptions===null)unavailable($('subscriptionRows'));else table($('subscriptionRows'),['user','plan','status','mode','updated','reference','payments'],data.subscriptions.filter(x=>environment(x)&&matches(x)&&($('planFilter').value==='all'||x.plan===$('planFilter').value)).map(s=>[person(s),s.plan==='pro'?'AI Pro':'AI Starter',statusLabel(s.status),t(s.test_mode?'sandbox':'live'),date(s.updated_at),ref(s.subscription_id),/^I-[A-Z0-9]+$/.test(s.subscription_id)?button('payments',()=>loadPayments(s.subscription_id)):'—']));
 renderCoaches();
 $('bookingAvailability').textContent=data.bookingEnabled?'':t('bookingClosed');
 if(data.bookings===null)unavailable($('sessionRows'));else table($('sessionRows'),['user','coach','time','status','paymentStatus','amount','mode','reference'],data.bookings.filter(x=>environment(x)&&matches(x)&&($('sessionFilter').value==='all'||x.status===$('sessionFilter').value)).map(b=>[person(b),b.coach_name||'—',date(b.starts_at),statusLabel(b.status),t(b.payment_verified?'verified':'notVerified'),money(b.price_cents),t(b.test_mode?'sandbox':'live'),ref(b.id,[b.order_id,b.capture_id].filter(Boolean).join(' / '))]));
 if(data.paymob===null)unavailable($('paymobRows'));else table($('paymobRows'),['user','status','amount','mode','created','reference'],data.paymob.filter(x=>environment(x)&&matches(x)).map(p=>[person(p),statusLabel(p.status),money(p.amount_cents,p.currency),t('sandbox'),date(p.created_at),ref(p.reference,p.order_id)]));
 if(data.accounts===null)unavailable($('accountRows'));else table($('accountRows'),['user','plan','confirmedEmail','created'],data.accounts.filter(matches).map(u=>{const active=data.subscriptions?.filter(s=>s.user_id===u.id&&!s.test_mode&&s.status==='active');const plan=data.subscriptions===null?'—':active.some(s=>s.plan==='pro')?'AI Pro':active.some(s=>s.plan==='starter')?'AI Starter':t('free');return [person({...u,user_id:u.id,account_name:u.name}),plan,t(u.confirmed?'yes':'no'),date(u.created_at)];}));
 if(data.warnings.length){$('adminNotice').textContent=t('partial')+' '+data.warnings.map(k=>t({accounts:'accounts',subscriptions:'subscriptions',coaches:'coaches',slots:'time',bookings:'sessions',paymob:'paymob'}[k])).join(' · ');}
 else if(!noticeKey)$('adminNotice').textContent=t('updated')+': '+date(data.generatedAt);
 renderPayments();
 const requested=new URLSearchParams(location.search).get('review');if(!reviewFocused&&/^[0-9a-f-]{36}$/i.test(requested||'')){const target=document.getElementById('coach-'+requested);if(target){target.style.outline='3px solid #b89bff';target.scrollIntoView({block:'center'});reviewFocused=true;}}
}
function renderCoaches(){const root=$('coachRows');root.replaceChildren();if(data.coaches===null)return unavailable(root);const list=data.coaches.filter(c=>matches(c)&&($('coachFilter').value==='all'||c.status===$('coachFilter').value));if(!list.length){root.append(node('p',t('empty'),'admin-empty'));return;}
 for(const c of list){const card=node('article',null,'admin-coach');card.id='coach-'+c.id;card.append(node('h3',c.name),node('p',statusLabel(c.status),'coach-state'),person(c),node('p',c.specialty),node('p',c.bio),node('p',c.languages),node('p',money(c.price_cents)),node('small',t('created')+': '+date(c.created_at)));const actions=node('div',null,'actions');if(c.linkedin_url){const a=node('a','LinkedIn','btn secondary');a.href=c.linkedin_url;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}for(const [kind,enabled,label] of [['cv',Boolean(c.cv_name),'viewCV'],['photo',c.has_photo,'viewPhoto']])if(enabled)actions.append(button(label,async()=>{const d=await request('/api/coaching',{action:kind,coach_id:c.id});const a=node('a');a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}));card.append(actions);
 if(c.status!=='approved'){const form=node('form'),hostLabel=node('label',t('zoomHost')),host=node('input');host.name='zoom_host_id';host.required=true;hostLabel.append(host);const attLabel=node('label',null,'attest'),att=node('input');att.type='checkbox';att.required=true;attLabel.append(att,node('span',t('reviewAttest')));const approve=node('button',t('approve'),'btn primary');approve.type='submit';form.append(attLabel,approve);form.onsubmit=async e=>{e.preventDefault();approve.disabled=true;try{await request('/api/coaching',{action:'review',coach_id:c.id,status:'approved',review_confirmed:att.checked});message('saved');await load();}catch{message('error');}finally{approve.disabled=false;}};card.append(form);}
 if(c.status==='approved'){card.append(node('p',t(c.has_host?'bookingActive':'awaitingZoom')));if(!c.has_host){const form=node('form'),label=node('label',t('zoomHost')),host=node('input');host.required=true;label.append(host);const confirm=node('label',null,'attest'),check=node('input');check.type='checkbox';check.required=true;confirm.append(check,node('span',t('zoomReady')));const activate=node('button',t('activate'),'btn primary');activate.type='submit';form.append(label,confirm,activate);form.onsubmit=async e=>{e.preventDefault();activate.disabled=true;try{await request('/api/coaching',{action:'activate',coach_id:c.id,zoom_host_id:host.value.trim(),zoom_ready:check.checked});message('saved');await load();}catch{message('error');}finally{activate.disabled=false;}};card.append(form);}}
 if(c.status!=='paused')card.append(button('pause',async()=>{await request('/api/coaching',{action:'review',coach_id:c.id,status:'paused'});message('saved');await load();}));root.append(card);
 }
}
async function loadPayments(id){message('loading');paymentData=null;$('paymentDetails').hidden=false;$('paymentDetailRows').replaceChildren(node('p',t('loading')));$('paymentDetails').scrollIntoView({block:'start',behavior:'smooth'});try{paymentData=await request('/api/admin?subscription='+encodeURIComponent(id));message('');renderPayments();}catch{message('error');unavailable($('paymentDetailRows'));}}
function renderPayments(){if(!paymentData)return;const p=paymentData,root=$('paymentDetailRows');root.replaceChildren(node('p',p.subscriptionId+' · '+t(p.test_mode?'sandbox':'live')),node('p',t('provider')+': '+p.providerStatus),node('p',t('nextBilling')+': '+date(p.nextBilling)));if(p.lastPayment)root.append(node('p',t('lastPayment')+': '+money(Number(p.lastPayment.amount)*100,p.lastPayment.currency)+' · '+date(p.lastPayment.time)));const rows=node('div');root.append(rows);table(rows,['reference','status','time','amount'],p.transactions.map(x=>[x.id,x.status,date(x.time),money(Number(x.amount)*100,x.currency)]));}
async function load(){if(!session()){data=null;$('adminContent').hidden=true;message('signin');return;}message('loading');$('refreshAdmin').disabled=true;try{data=await request('/api/admin');message('');render();}catch(e){data=null;$('adminContent').hidden=true;message(e.status===401?'signin':e.status===403?'denied':'error');}finally{$('refreshAdmin').disabled=false;}}
function apply(){const code=languages[language].code;document.documentElement.lang=code;document.documentElement.dir=code==='ar'?'rtl':'ltr';document.title=t('title');$('adminLanguage').value=language;$('adminLanguage').setAttribute('aria-label',translate('language',language));document.querySelectorAll('[data-admin]').forEach(el=>el.textContent=t(el.dataset.admin));for(const id of ['coachFilter','sessionFilter'])for(const option of $(id).options)option.textContent=option.value==='all'?t('all'):statusLabel(option.value);syncLanguageLinks(language);if(noticeKey)message(noticeKey);render();}
for(const [key,l] of Object.entries(languages)){const o=node('option',l.name);o.value=key;$('adminLanguage').append(o);}
$('adminLanguage').onchange=()=>{language=$('adminLanguage').value;rememberLanguage(language);apply();};$('refreshAdmin').onclick=load;for(const id of ['mode','planFilter','coachFilter','sessionFilter'])$(id).onchange=render;$('search').oninput=render;$('closePayments').onclick=()=>{$('paymentDetails').hidden=true;paymentData=null;};apply();await load();
